/* StrettoCharts visual aids: chart types matched to the data being communicated. */
(function(){
  const d=document,$=s=>d.querySelector(s),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
  let data=null,history=null,lastProfile='';
  const good=x=>x?.sources?.flatMap(s=>(s.entries||[]).filter(e=>s.status==='ok'&&Number.isFinite(+e.rank)).map(e=>({...e,source:s.name})))||[];
  const norm=s=>String(s??'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
  function style(){if($('#stretto-visual-aids-css'))return;const s=d.createElement('style');s.id='stretto-visual-aids-css';s.textContent=`
    .sc-viz{background:#fff;border:1px solid #e4e4ed;border-radius:18px;padding:16px;box-shadow:0 6px 20px #24243b0b}.sc-viz-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:12px}.sc-viz-head h3{margin:0;font-size:14px;letter-spacing:-.02em;color:#171722}.sc-viz-head p{margin:4px 0 0;color:#717282;font-size:10px;line-height:1.45}.sc-viz-value{font-size:17px;font-weight:900;white-space:nowrap}.sc-profile-viz{margin-top:13px}.sc-rank-bars{display:grid;gap:9px}.sc-rank-row{display:grid;grid-template-columns:minmax(100px,1fr) 1.8fr 34px;gap:9px;align-items:center}.sc-rank-label{font-size:10px;font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.sc-rank-track{height:9px;background:#ececf3;border-radius:99px;overflow:hidden}.sc-rank-fill{display:block;height:100%;border-radius:99px;background:#7657ff}.sc-rank-no{text-align:right;font-size:11px;font-weight:900}.sc-viz-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}.sc-mini-svg{display:block;width:100%;height:auto}.sc-gridline{stroke:#e9e9ef;stroke-width:1}.sc-bar{fill:#7657ff}.sc-axis-text{font-size:9px;fill:#717282}.sc-legend{margin-top:8px;color:#717282;font-size:9px}@media(max-width:700px){.sc-viz-grid{grid-template-columns:1fr}.sc-rank-row{grid-template-columns:82px 1fr 32px}.sc-viz{padding:14px}}`;d.head.appendChild(s)}
  function currentProfileEntries(){const p=$('#results .profile');if(!p||!data)return[];const name=p.querySelector('.profile-name')?.textContent.trim()||'',kind=p.querySelector('.profile-kind')?.textContent.replace(' profile','').trim()||'Song',summary=p.querySelector('.profile-summary')?.textContent||'',artist=(summary.match(/\bby\s+(.+?)\s+—/)||[])[1]||'',n=norm(name),a=norm(artist);return good(data).filter(e=>kind==='Artist'?(e.artists||[]).some(x=>norm(x)===n):kind==='Album'?norm(e.album||e.albumName||e.release||e.releaseTitle)===n&&(!a||(e.artists||[]).some(x=>norm(x)===a)):norm(e.title)===n&&(!a||(e.artists||[]).some(x=>norm(x)===a)))}
  function profileVisual(){const p=$('#results .profile');if(!p)return;const key=p.querySelector('.profile-kind')?.textContent+'::'+p.querySelector('.profile-name')?.textContent;if(key===lastProfile)return;lastProfile=key;const rows=currentProfileEntries().sort((a,b)=>+a.rank-+b.rank);if(!rows.length)return;const old=p.querySelector('.sc-profile-viz');if(old)old.remove();const max=Math.max(10,...rows.map(x=>+x.rank)),unique=[],seen=new Set();rows.forEach(x=>{if(!seen.has(x.source)){seen.add(x.source);unique.push(x)}});const shown=unique.slice(0,10),section=d.createElement('section');section.className='sc-viz sc-profile-viz';section.innerHTML=`<div class="sc-viz-head"><div><h3>Cross-chart performance</h3><p>Horizontal bars make current positions easy to compare; #1 is strongest.</p></div><strong class="sc-viz-value">${shown.length} charts</strong></div><div class="sc-rank-bars">${shown.map(x=>{const pct=Math.max(8,100-(+x.rank-1)/Math.max(max-1,1)*100);return `<div class="sc-rank-row"><span class="sc-rank-label" title="${esc(x.source)}">${esc(x.source)}</span><div class="sc-rank-track"><i class="sc-rank-fill" style="width:${pct.toFixed(1)}%"></i></div><b class="sc-rank-no">#${+x.rank}</b></div>`}).join('')}</div>`;(p.querySelector('.profile-stats')||p).parentNode.appendChild(section)}
  function movementVisual(){const a=$('#analytics');if(!a||!data)return;let host=a.querySelector('.sc-analytics-visuals');if(!host){host=d.createElement('div');host.className='sc-analytics-visuals';a.appendChild(host)}const es=good(data),moves=es.map(e=>+e.movement).filter(Number.isFinite),ranks=es.map(e=>+e.rank),bins=[1,10,20,30,40,50,60,70,80,100],counts=bins.map((b,i)=>ranks.filter(r=>i===0?r<=b:r>bins[i-1]&&r<=b).length),mx=Math.max(...counts,1),up=moves.filter(x=>x>0).reduce((a,b)=>a+b,0),down=moves.filter(x=>x<0).reduce((a,b)=>a+Math.abs(b),0),recent=history?.map(x=>good(x).length)||[],w=760,h=240,pad=38,base=190;
    const maxMove=Math.max(up,down,1),barH=v=>Math.max(v?4:0,v/maxMove*120);
    const trend=recent.length>1?recent.map((v,i)=>{const x=pad+i*(w-pad*2)/Math.max(recent.length-1,1),y=base-(v/Math.max(...recent,1))*120;return`${x.toFixed(1)},${y.toFixed(1)}`}).join(' '):'';
    host.innerHTML=`<div class="sc-viz-grid">
      <section class="sc-viz"><div class="sc-viz-head"><div><h3>Rank distribution</h3><p>Discrete rank bands are shown as bars because these are bucket counts, not a time series.</p></div><strong class="sc-viz-value">${ranks.length}</strong></div><svg class="sc-mini-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="Current rank distribution bar chart"><line class="sc-gridline" x1="${pad}" y1="${base}" x2="${w-pad}" y2="${base}"/>${counts.map((v,i)=>{const x=pad+i*70,bh=v/mx*130,y=base-bh;return `<rect class="sc-bar" x="${x-20}" y="${y}" width="40" height="${bh}" rx="6"><title>Ranks ${i===0?'#1–#1':`#${bins[i-1]+1}–#${bins[i]}`}: ${v} entries</title></rect><text class="sc-axis-text" x="${x}" y="${base+18}" text-anchor="middle">${i===0?'#1':`≤${bins[i]}`}</text><text class="sc-axis-text" x="${x}" y="${Math.max(y-6,10)}" text-anchor="middle">${v}</text>`}).join('')}</svg></section>
      <section class="sc-viz"><div class="sc-viz-head"><div><h3>Movement balance</h3><p>A diverging comparison is clearer for upward versus downward movement.</p></div><strong class="sc-viz-value">${moves.length} moves</strong></div><svg class="sc-mini-svg" viewBox="0 0 760 240" role="img" aria-label="Upward and downward chart movement"><line class="sc-gridline" x1="380" y1="35" x2="380" y2="190"/><rect class="sc-bar" x="380" y="${190-barH(up)}" width="${Math.min(300,barH(up)*2.5)}" height="${barH(up)}" rx="8" transform="rotate(180 380 ${190-barH(up)/2})"/><rect x="380" y="${190-barH(down)}" width="${Math.min(300,barH(down)*2.5)}" height="${barH(down)}" rx="8" transform="rotate(0 380 ${190-barH(down)/2})" fill="#d9d9e3"/><text class="sc-axis-text" x="350" y="215" text-anchor="end">Upward movement · ${up}</text><text class="sc-axis-text" x="410" y="215">Downward movement · ${down}</text></svg><div class="sc-legend">Only source-supplied movement values are included.</div></section>
      ${trend?`<section class="sc-viz" style="grid-column:1/-1"><div class="sc-viz-head"><div><h3>Coverage trajectory</h3><p>A line chart is used because snapshots are ordered through time.</p></div><strong class="sc-viz-value">${recent.length} snapshots</strong></div><svg class="sc-mini-svg" viewBox="0 0 ${w} ${h}" role="img" aria-label="Coverage trajectory line chart"><polyline fill="none" stroke="#7657ff" stroke-width="3" stroke-linecap="round" stroke-linejoin="round" points="${trend}"/>${recent.map((v,i)=>{const x=pad+i*(w-pad*2)/Math.max(recent.length-1,1),y=base-(v/Math.max(...recent,1))*120;return`<circle cx="${x}" cy="${y}" r="3" fill="#7657ff"><title>${v} entries</title></circle>`}).join('')}</svg></section>`:''}
    </div>`}
  async function init(){style();try{const r=await fetch('data/latest.json?visuals='+Date.now(),{cache:'no-store'});if(r.ok)data=await r.json()}catch(_){}try{const r=await fetch('data/history/index.json?visuals='+Date.now(),{cache:'no-store'});if(r.ok){const dates=await r.json(),xs=await Promise.all(dates.map(async x=>{try{const q=await fetch('data/history/'+x+'.json?visuals='+Date.now(),{cache:'no-store'});return q.ok?await q.json():null}catch(_){return null}}));history=xs.filter(Boolean)}}catch(_){history=[]}profileVisual();movementVisual();const root=$('#results');if(root)new MutationObserver(()=>profileVisual()).observe(root,{childList:true,subtree:true})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
