import { mkdir, writeFile, readFile } from 'node:fs/promises';

const ROOT = new URL('..', import.meta.url);
const DATA_DIR = new URL('./data/', ROOT);
const LATEST = new URL('./data/latest.json', ROOT);
const HISTORY_DIR = new URL('./data/history/', ROOT);
const HISTORY_INDEX = new URL('./data/history/index.json', ROOT);

const SOURCES = [
  { id: 'spotify-global-daily', name: 'Spotify Global Daily', type: 'daily', url: 'https://charts.spotify.com/charts/view/regional-global-daily/latest/download', parser: parseSpotifyCsv },
  { id: 'spotify-global-weekly', name: 'Spotify Global Weekly Top Songs', type: 'weekly', url: 'https://charts.spotify.com/charts/view/regional-global-weekly/latest/download', parser: parseSpotifyCsv },
  { id: 'apple-global-daily', name: 'Apple Music Global Top 100', type: 'daily', url: 'https://rss.applemarketingtools.com/api/v2/us/music/most-played/100/songs.json', parser: parseAppleRss },
  { id: 'apple-australia-daily', name: 'Apple Music Australia Top 100', type: 'daily', url: 'https://rss.applemarketingtools.com/api/v2/au/music/most-played/100/songs.json', parser: parseAppleRss },
  { id: 'youtube-global-daily', name: 'YouTube Global Top Songs Daily', type: 'daily', url: 'https://charts.youtube.com/youtubei/v1/browse?alt=json&key=AIzaSyCzEW7JUJdSql-0V4tHUb6laYm4iAE_dM', parser: parseYouTubeApi, parserArgs: { chart: 'daily', kind: 'tracks' } },
  { id: 'youtube-global-weekly', name: 'YouTube Global Top Songs Weekly', type: 'weekly', url: 'https://charts.youtube.com/youtubei/v1/browse?alt=json&key=AIzaSyCzEW7JUJdSql-0V4tHUb6laYm4iAE_dM', parser: parseYouTubeApi, parserArgs: { chart: 'weekly', kind: 'tracks' } },
  { id: 'youtube-global-artists-weekly', name: 'YouTube Global Top Artists Weekly', type: 'weekly', url: 'https://charts.youtube.com/youtubei/v1/browse?alt=json&key=AIzaSyCzEW7JUJdSql-0V4tHUb6laYm4iAE_dM', parser: parseYouTubeApi, parserArgs: { chart: 'weekly', kind: 'artists' } },
  { id: 'deezer-global', name: 'Deezer Global Top Tracks', type: 'daily', url: 'https://api.deezer.com/chart/0/tracks?limit=100', parser: parseDeezerJson },
  { id: 'shazam-us-weekly', name: 'Shazam US Top 200', type: 'weekly', url: 'https://www.shazam.com/services/charts/csv/top-200/united-states', parser: parseShazamCsv },
  { id: 'aria-australia-weekly', name: 'ARIA Top 50 Singles', type: 'weekly', url: 'https://www.aria.com.au/charts/singles-chart', parser: parseAriaHtml },
  { id: 'official-uk-singles-weekly', name: 'Official UK Singles Top 100', type: 'weekly', url: 'https://www.officialcharts.com/charts/singles-chart/', parser: parseOfficialChartsHtml },
  { id: 'billboard-hot-100', name: 'Billboard Hot 100', type: 'weekly', url: 'https://www.billboard.com/charts/hot-100/', parser: parseBillboardJson, dataUrl: 'https://raw.githubusercontent.com/mhollingshead/billboard-hot-100/main/recent.json' },
  { id: 'billboard-global-200', name: 'Billboard Global 200', type: 'weekly', url: 'https://www.billboard.com/charts/billboard-global-200/', parser: parseBillboardJson, dataUrl: 'https://raw.githubusercontent.com/KoreanThinker/billboard-json/main/billboard-global-200/recent.json' },
];

const DEFAULT_HEADERS = { 'user-agent': 'StrettoCharts/1.0 (+https://github.com/Tezzaaaaaa/StrettoCharts)', accept: 'text/html,application/json,text/csv;q=0.9,*/*;q=0.8' };
function clean(value) { return String(value ?? '').replace(/\s+/g, ' ').trim(); }
function key(title, artists = []) { return `${clean(title).toLowerCase()}::${artists.map(clean).join('|').toLowerCase()}`; }
function csvRows(text) { const rows = []; let row = [], field = '', quoted = false; for (let i = 0; i < text.length; i++) { const c = text[i]; if (c === '"') { if (quoted && text[i + 1] === '"') { field += '"'; i++; } else quoted = !quoted; } else if (c === ',' && !quoted) { row.push(field); field = ''; } else if ((c === '\n' || c === '\r') && !quoted) { if (c === '\r' && text[i + 1] === '\n') i++; row.push(field); field = ''; if (row.some(v => clean(v))) rows.push(row); row = []; } else field += c; } if (field || row.length) { row.push(field); rows.push(row); } return rows; }
function stripHtml(value) { return clean(String(value ?? '').replace(/<[^>]+>/g, '')); }
function parseSpotifyCsv(text) { const rows = csvRows(text); if (rows.length < 2) throw new Error('Spotify CSV contained no rows'); const headers = rows[0].map(clean); const index = n => headers.findIndex(h => h.toLowerCase() === n); const rank = index('rank'), title = index('track_name'), artist = index('artist_names'), streams = index('streams'), date = index('date'), region = index('region'); if (rank < 0 || title < 0 || artist < 0) throw new Error(`Unexpected Spotify CSV schema: ${headers.slice(0, 12).join(', ')}`); return rows.slice(1).map(r => ({ rank: Number(r[rank]), title: clean(r[title]), artists: clean(r[artist]).split(',').map(clean).filter(Boolean), streams: streams >= 0 ? Number(r[streams]) || null : null, chartDate: date >= 0 ? clean(r[date]) : null, region: region >= 0 ? clean(r[region]) : 'Global' })).filter(x => Number.isFinite(x.rank) && x.title); }
function parseAppleRss(text) { const json = JSON.parse(text); const results = Array.isArray(json.feed?.results) ? json.feed.results : []; return results.map((item, i) => ({ rank: i + 1, title: clean(item.name), artists: [clean(item.artistName)].filter(Boolean), album: clean(item.collectionName) || null, url: item.url || null, artworkUrl: item.artworkUrl100 || null, chartDate: json.feed?.updated || null })).filter(x => x.title); }
function parseDeezerJson(text) { const json = JSON.parse(text); const rows = Array.isArray(json.data) ? json.data : []; return rows.map((item, i) => ({ rank: i + 1, title: clean(item.title), artists: [clean(item.artist?.name)].filter(Boolean), album: clean(item.album?.title) || null, url: item.link || null, artworkUrl: item.album?.cover_medium || null })).filter(x => x.title); }
function youtubeBody(chart, kind) { const type = chart === 'daily' ? 'daily' : 'weekly'; const selected = kind === 'artists' ? 'ARTISTS' : 'TRACKS'; return { browseId: 'FEmusic_analytics_charts_home', context: { capabilities: {}, client: { clientName: 'WEB_MUSIC_ANALYTICS', clientVersion: '0.2', experimentIds: [], experimentsToken: '', gl: 'US', hl: 'en', theme: 'MUSIC' }, request: { internalExperimentFlags: [] } }, query: `chart_params_type=${type === 'daily' ? 'DAY' : 'WEEK'}&perspective=CHART&flags=viral_video_chart&selected_chart=${selected}&chart_params_id=${type}:0:0` }; }
function parseYouTubeApi(text, args) { const json = JSON.parse(text); const root = json?.contents?.sectionListRenderer?.contents?.[0]?.musicAnalyticsSectionRenderer; if (!root) throw new Error('YouTube Charts API response missing musicAnalyticsSectionRenderer'); const content = root.content || {}; if (args.kind === 'artists') { const views = content.artists?.[0]?.artistViews; if (!Array.isArray(views)) throw new Error('YouTube artist chart response missing artistViews'); return views.map((item, i) => ({ rank: Number(item.rank ?? i + 1), title: clean(item.name || item.title || item.artist), artists: [clean(item.name || item.title || item.artist)].filter(Boolean), chartDate: root.perspectiveMetadata?.title || null })).filter(x => x.rank > 0 && x.title).slice(0, 100); } const tracks = content.trackTypes?.[0]?.trackViews; if (!Array.isArray(tracks)) throw new Error('YouTube song chart response missing trackViews'); return tracks.map((item, i) => ({ rank: Number(item.rank ?? i + 1), title: clean(item.name || item.title), artists: Array.isArray(item.artists) ? item.artists.map(a => clean(a.name || a.title || a)).filter(Boolean) : [clean(item.artist)].filter(Boolean), chartDate: root.perspectiveMetadata?.title || null })).filter(x => x.rank > 0 && x.title).slice(0, 200); }
function parseShazamCsv(text) { const rows = csvRows(text); if (rows.length < 2) throw new Error('Shazam CSV contained no rows'); const headers = rows[0].map(clean).map(h => h.toLowerCase()); const find = (...names) => names.map(n => headers.indexOf(n)).find(i => i >= 0) ?? -1; const rank = find('rank', 'position'), title = find('title', 'track', 'song'), artist = find('artist', 'artist name', 'artists'); if (title < 0 || artist < 0) throw new Error(`Unexpected Shazam CSV schema: ${headers.slice(0, 15).join(', ')}`); return rows.slice(1).map((r, i) => ({ rank: rank >= 0 ? Number(r[rank]) : i + 1, title: clean(r[title]), artists: clean(r[artist]).split(/,|&/).map(clean).filter(Boolean) })).filter(x => Number.isFinite(x.rank) && x.title && x.artists.length).slice(0, 200); }
function parseAriaHtml(text) { const normalized = text.replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' '); const lines = normalized.replace(/<[^>]+>/g, '\n').replace(/&amp;/g, '&').replace(/&#39;/g, "'").replace(/&quot;/g, '"').split(/\n+/).map(clean).filter(Boolean), out = []; for (let i = 0; i < lines.length && out.length < 50; i++) { if (!/^\d+$/.test(lines[i])) continue; const rank = Number(lines[i]); if (rank < 1 || rank > 50) continue; const title = lines[i + 1], artist = lines[i + 2]; if (!title || !artist || /^\d+$/.test(title)) continue; out.push({ rank, title, artists: artist.split(',').map(clean).filter(Boolean) }); } if (!out.length) throw new Error('ARIA markup did not expose chart rows'); return dedupeByRank(out); }
function parseOfficialChartsHtml(text) { const normalized = text.replace(/<script[\s\S]*?<\/script>/gi, ' ').replace(/<style[\s\S]*?<\/style>/gi, ' '); const lines = normalized.replace(/<[^>]+>/g, '\n').replace(/&amp;/g, '&').replace(/&#39;/g, "'").replace(/&quot;/g, '"').split(/\n+/).map(clean).filter(Boolean), out = []; for (let i = 0; i < lines.length && out.length < 100; i++) { if (!/^Number\s*\d+$/i.test(lines[i])) continue; const rank = Number(lines[i].match(/\d+/)[0]); const title = lines[i + 1], artist = lines[i + 2]; if (title && artist) out.push({ rank, title, artists: artist.split(/[\/]/).map(clean).filter(Boolean) }); } if (!out.length) throw new Error('Official Charts markup did not expose chart rows'); return dedupeByRank(out); }
function parseBillboardJson(text) { const json = JSON.parse(text); const rows = Array.isArray(json.data) ? json.data : []; if (!rows.length) throw new Error('Billboard JSON contained no chart rows'); return rows.map(item => ({ rank: Number(item.this_week ?? item.rank), title: clean(item.song ?? item.name), artists: clean(item.artist).split(/,|&/).map(clean).filter(Boolean), previousRank: item.last_week ?? item.last_week_rank ?? null, peakRank: item.peak_position ?? item.peak_rank ?? null, weeksOnChart: item.weeks_on_chart ?? null, chartDate: json.date ?? null })).filter(x => Number.isFinite(x.rank) && x.title && x.artists.length); }
function dedupeByRank(rows) { return [...new Map(rows.map(row => [row.rank, row])).values()].sort((a, b) => a.rank - b.rank); }
async function fetchSource(source) { const url = source.dataUrl || source.url; const options = { headers: { ...DEFAULT_HEADERS } }; if (source.id.startsWith('youtube-')) { options.method = 'POST'; options.headers['content-type'] = 'application/json'; options.body = JSON.stringify(youtubeBody(source.parserArgs.chart, source.parserArgs.kind)); } const response = await fetch(url, options); if (!response.ok) throw new Error(`HTTP ${response.status} from ${url}`); const entries = source.id.startsWith('youtube-') ? source.parser(await response.text(), source.parserArgs) : source.parser(await response.text()); if (!entries.length) throw new Error('No chart entries parsed'); return entries; }
function addMovement(current, previous) { const previousByKey = new Map((previous?.entries || []).map(e => [key(e.title, e.artists), e])); return current.map(e => { const old = previousByKey.get(key(e.title, e.artists)); const movement = old ? old.rank - e.rank : null; return { ...e, previousRank: e.previousRank ?? old?.rank ?? null, movement, movementLabel: movement === null ? 'new' : movement > 0 ? `up ${movement}` : movement < 0 ? `down ${Math.abs(movement)}` : 'same', peakRank: Math.min(e.peakRank ?? e.rank, old?.peakRank ?? e.rank), weeksOnChart: e.weeksOnChart ?? ((old?.weeksOnChart || 0) + 1) }; }); }
function calculateArtistRankings(sources) { const map = new Map(); for (const source of sources) for (const entry of source.entries || []) for (const artist of entry.artists || []) { const name = clean(artist); if (!name) continue; const id = name.toLowerCase(); const row = map.get(id) || { artist: name, appearances: 0, totalPoints: 0, bestRank: null, charts: 0 }; row.appearances++; row.totalPoints += Math.max(0, 101 - entry.rank); row.bestRank = row.bestRank === null ? entry.rank : Math.min(row.bestRank, entry.rank); row.charts++; map.set(id, row); } return [...map.values()].sort((a, b) => b.totalPoints - a.totalPoints || b.appearances - a.appearances || a.bestRank - b.bestRank).map((x, i) => ({ ...x, rank: i + 1 })); }
async function main() { await mkdir(DATA_DIR, { recursive: true }); await mkdir(HISTORY_DIR, { recursive: true }); const updatedAt = new Date().toISOString(); let previous = null; try { previous = JSON.parse(await readFile(LATEST, 'utf8')); } catch {} const results = await Promise.all(SOURCES.map(async source => { try { const raw = await fetchSource(source); const old = previous?.sources?.find(s => s.id === source.id); const entries = addMovement(raw, old); console.log(`OK ${source.name}: ${entries.length}`); return { id: source.id, name: source.name, type: source.type, sourceUrl: source.url, dataUrl: source.dataUrl || null, status: 'ok', fetchedAt: updatedAt, count: entries.length, entries }; } catch (error) { const message = error instanceof Error ? error.message : String(error); console.error(`ERROR ${source.name}: ${message}`); return { id: source.id, name: source.name, type: source.type, sourceUrl: source.url, dataUrl: source.dataUrl || null, status: 'error', fetchedAt: updatedAt, count: 0, error: message, entries: [] }; } })); const ok = results.filter(x => x.status === 'ok'); const payload = { schemaVersion: 3, generatedAt: updatedAt, sources: results, artistRankings: calculateArtistRankings(ok) }; await writeFile(LATEST, JSON.stringify(payload, null, 2) + '\n', 'utf8'); if (ok.length) { const date = updatedAt.slice(0, 10); await writeFile(new URL(`./${date}.json`, HISTORY_DIR), JSON.stringify(payload, null, 2) + '\n', 'utf8'); let index = []; try { index = JSON.parse(await readFile(HISTORY_INDEX, 'utf8')); } catch {} if (!index.includes(date)) index.push(date); index.sort().reverse(); await writeFile(HISTORY_INDEX, JSON.stringify(index, null, 2) + '\n', 'utf8'); } console.log(`Updated ${ok.length}/${results.length} sources at ${updatedAt}`); }
main().catch(error => { console.error(error); process.exit(1); });
