import { mkdir, writeFile, readFile } from 'node:fs/promises';
const ROOT=new URL('..',import.meta.url),DATA_DIR=new URL('./data/',ROOT),LATEST=new URL('./data/latest.json',ROOT),HISTORY_DIR=new URL('./data/history/',ROOT),HISTORY_INDEX=new URL('./data/history/index.json',ROOT);
const YOUTUBE='https://charts.youtube.com/youtubei/v1/browse?alt=json&key=AIzaSyCzEW7JUJdSql-0-2V4tHUb6laYm4iAE_dM';
const SOURCES=[
{id:'spotify-global-daily',name:'Spotify Global Daily',type:'daily',url:'https://charts.spotify.com/charts/view/regional-global-daily/latest',parser:parseSpotifyCsv},
{id:'spotify-global-weekly',name:'Spotify Global Weekly Top Songs',type:'weekly',url:'https://charts.spotify.com/charts/view/regional-global-weekly/latest',parser:parseSpotifyCsv},
{id:'apple-global-daily',name:'Apple Music Global Top 100',type:'daily',url:'https://rss.applemarketingtools.com/api/v2/us/music/most-played/100/songs.json',parser:parseAppleRss},
{id:'apple-australia-daily',name:'Apple Music Australia Top 100',type:'daily',url:'https://rss.applemarketingtools.com/api/v2/au/music/most-played/100/songs.json',parser:parseAppleRss},
{id:'youtube-global-daily',name:'YouTube Global Top Songs Daily',type:'daily',url:YOUTUBE,parser:parseYouTubeApi,args:{chart:'daily',kind:'tracks'}},
{id:'youtube-global-weekly',name:'YouTube Global Top Songs Weekly',type:'weekly',url:YOUTUBE,parser:parseYouTubeApi,args:{chart:'weekly',kind:'tracks'}},
{id:'youtube-global-artists-weekly',name:'YouTube Global Top Artists Weekly',type:'weekly',url:YOUTUBE,parser:parseYouTubeApi,args:{chart:'weekly',kind:'artists'}},
{id:'deezer-global',name:'Deezer Global Top Tracks',type:'daily',url:'https://api.deezer.com/chart/0/tracks?limit=100',parser:parseDeezer},
{id:'shazam-us-weekly',name:'Shazam US Top 200',type:'weekly',url:'https://www.shazam.com/services/charts/csv/top-200/united-states',parser:parseShazam},
{id:'aria-australia-weekly',name:'ARIA Top 50 Singles',type:'weekly',url:'https://www.aria.com.au/charts/singles-chart',parser:parseAria},
{id:'official-uk-singles-weekly',name:'Official UK Singles Top 100',type:'weekly',url:'https://www.officialcharts.com/charts/singles-chart/',dataUrl:'https://raw.githubusercontent.com/KoreanThinker/billboard-json/main/official-uk-songs/recent.json',parser:parseBillboardJson},
{id:'billboard-hot-100',name:'Billboard Hot 100',type:'weekly',url:'https://www.billboard.com/charts/hot-100/',dataUrl:'https://raw.githubusercontent.com/mhollingshead/billboard-hot-100/main/recent.json',parser:parseBillboardJson},
{id:'billboard-global-200',name:'Billboard Global 200',type:'weekly',url:'https://www.billboard.com/charts/billboard-global-200/',dataUrl:'https://api.github.com/repos/KoreanThinker/billboard-json/contents/billboard-global-200/recent.json',parser:parseGitHubJson}
];
const HEADERS={'user-agent':'StrettoCharts/1.0 (+https://github.com/Tezzaaaaaa/StrettoCharts)','accept':'text/html,application/json,text/csv;q=0.9,*/*;q=0.8'};
const clean=v=>String(v??'').replace(/\s+/g,' ').trim(),key=(t,a=[])=>`${clean(t).toLowerCase()}::${a.map(clean).join('|').toLowerCase()}`;
function rows(text){const o=[];let r=[],f='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(q&&text[i+1]==='"'){f+='"';i++;}else q=!q;}else if(c===','&&!q){r.push(f);f='';}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&text[i+1]==='\n')i++;r.push(f);f='';if(r.some(x=>clean(x)))o.push(r);r=[];}else f+=c;}if(f||r.length){r.push(f);o.push(r);}return o;}
function parseSpotifyCsv(text){const r=rows(text);if(r.length<2)throw Error('Spotify CSV contained no rows');const h=r[0].map(clean),i=n=>h.findIndex(x=>x.toLowerCase()===n),rank=i('rank'),title=i('track_name'),artist=i('artist_names'),streams=i('streams');if(rank<0||title<0||artist<0)throw Error(`Unexpected Spotify CSV schema: ${h.slice(0,12).join(', ')}`);return r.slice(1).map(x=>({rank:Number(x[rank]),title:clean(x[title]),artists:clean(x[artist]).split(',').map(clean).filter(Boolean),streams:streams>=0?Number(x[streams])||null:null})).filter(x=>Number.isFinite(x.rank)&&x.title);}
function parseAppleRss(t){const j=JSON.parse(t);return(j.feed?.results||[]).map((x,i)=>({rank:i+1,title:clean(x.name),artists:[clean(x.artistName)].filter(Boolean),album:clean(x.collectionName)||null,url:x.url||null,artworkUrl:x.artworkUrl100||null})).filter(x=>x.title);}
function parseDeezer(t){const j=JSON.parse(t);return(j.data||[]).map((x,i)=>({rank:i+1,title:clean(x.title),artists:[clean(x.artist?.name)].filter(Boolean),album:clean(x.album?.title)||null,url:x.link||null,artworkUrl:x.album?.cover_medium||null})).filter(x=>x.title);}
function youtubeBody(chart,kind){const type=chart==='daily'?'daily':'weekly';return{browseId:'FEmusic_analytics_charts_home',context:{capabilities:{},client:{clientName:'WEB_MUSIC_ANALYTICS',clientVersion:'0.2',experimentIds:[],experimentsToken:'',gl:'US',hl:'en',theme:'MUSIC'},request:{internalExperimentFlags:[]}},query:`chart_params_type=${type==='daily'?'DAY':'WEEK'}&perspective=CHART&flags=viral_video_chart&selected_chart=${kind==='artists'?'ARTISTS':'TRACKS'}&chart_params_id=${type}:0:0`};}
function parseYouTube(t,a){const j=JSON.parse(t),root=j?.contents?.sectionListRenderer?.contents?.[0]?.musicAnalyticsSectionRenderer,c=root?.content;if(!c)throw Error('YouTube Charts API response missing chart content');if(a.kind==='artists'){const v=c.artists?.[0]?.artistViews;if(!Array.isArray(v))throw Error('YouTube artist chart response missing artistViews');return v.map((x,i)=>({rank:Number(x.rank??i+1),title:clean(x.name||x.title||x.artist),artists:[clean(x.name||x.title||x.artist)].filter(Boolean)})).filter(x=>x.title).slice(0,100);}const v=c.trackTypes?.[0]?.trackViews;if(!Array.isArray(v))throw Error('YouTube song chart response missing trackViews');return v.map((x,i)=>({rank:Number(x.rank??i+1),title:clean(x.title||x.name),artists:(x.artists||[]).map(y=>clean(y.name||y.title||y)).filter(Boolean)})).filter(x=>x.title).slice(0,200);}
function parseShazam(t){const r=rows(t);const hi=r.findIndex(x=>x.some(v=>/title|track|song/i.test(clean(v)))&&x.some(v=>/artist|subtitle/i.test(clean(v))));if(hi<0)throw Error(`Shazam CSV header not found: ${r[0]?.join(', ')||'empty'}`);const h=r[hi].map(clean).map(x=>x.toLowerCase()),find=(...n)=>n.map(x=>h.indexOf(x)).find(i=>i>=0)??-1,rank=find('rank','position'),title=find('title','track','song'),artist=find('artist','artist name','artists','subtitle');if(title<0||artist<0)throw Error(`Unexpected Shazam CSV schema: ${h.join(', ')}`);return r.slice(hi+1).map((x,k)=>({rank:rank>=0?Number(x[rank]):k+1,title:clean(x[title]),artists:clean(x[artist]).split(/,|&/).map(clean).filter(Boolean)})).filter(x=>Number.isFinite(x.rank)&&x.title&&x.artists.length).slice(0,200);}
function parseAria(t){const s=t.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,'\n').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"'),l=s.split(/\n+/).map(clean).filter(Boolean),o=[];for(let i=0;i<l.length&&o.length<50;i++){if(!/^\d+$/.test(l[i]))continue;const rank=Number(l[i]),title=l[i+1],artist=l[i+2];if(rank>=1&&rank<=50&&title&&artist&&!/^\d+$/.test(title))o.push({rank,title,artists:artist.split(',').map(clean).filter(Boolean)});}if(!o.length)throw Error('ARIA markup did not expose chart rows');return dedupe(o);}
function parseBillboardJson(t){const j=JSON.parse(t),r=j.data||[];if(!r.length)throw Error('Billboard JSON contained no chart rows');return r.map(x=>({rank:Number(x.this_week??x.rank),title:clean(x.song??x.name),artists:clean(x.artist).split(/,|&/).map(clean).filter(Boolean),previousRank:x.last_week??x.last_week_rank??null,peakRank:x.peak_position??x.peak_rank??null,weeksOnChart:x.weeks_on_chart??null,chartDate:j.date??null})).filter(x=>Number.isFinite(x.rank)&&x.title&&x.artists.length);}
function parseGitHubJson(t){const j=JSON.parse(t);if(!j.content)throw Error('GitHub content API returned no file content');return parseBillboardJson(Buffer.from(j.content.replace(/\s/g,''),'base64').toString('utf8'));}
function dedupe(a){return[...new Map(a.map(x=>[x.rank,x])).values()].sort((a,b)=>a.rank-b.rank);}
function dateBack(days){const d=new Date();d.setUTCDate(d.getUTCDate()-days);return d.toISOString().slice(0,10);}
async function get(url,opt={}){const r=await fetch(url,{...opt,headers:{...HEADERS,...(opt.headers||{})}});if(!r.ok)throw Error(`HTTP ${r.status} from ${url}`);return r.text();}
async function fetchSource(s){if(s.id==='spotify-global-daily'||s.id==='spotify-global-weekly'){const type=s.id.endsWith('daily')?'daily':'weekly',paths=[];for(let d=0;d<15;d++){const date=dateBack(d);paths.push(`https://charts.spotify.com/api/charts/regional/global/${type}/${date}`,`https://charts.spotify.com/data/regional-global-${type}/${date}.csv`);}let last='';for(const url of paths){try{return s.parser(await get(url));}catch(e){last=e.message;}}throw Error(last||'Spotify chart endpoint unavailable');}
if(s.id.startsWith('youtube-'))return s.parser(await get(s.url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(youtubeBody(s.args.chart,s.args.kind))}),s.args);
return s.parser(await get(s.dataUrl||s.url));}
function movement(cur,old){const m=new Map((old?.entries||[]).map(e=>[key(e.title,e.artists),e]));return cur.map(e=>{const p=m.get(key(e.title,e.artists)),mv=p?p.rank-e.rank:null;return{...e,previousRank:e.previousRank??p?.rank??null,movement:mv,movementLabel:mv===null?'new':mv>0?`up ${mv}`:mv<0?`down ${Math.abs(mv)}`:'same',peakRank:Math.min(e.peakRank??e.rank,p?.peakRank??e.rank),weeksOnChart:e.weeksOnChart??((p?.weeksOnChart||0)+1)};});}
function artistRankings(src){const m=new Map();for(const s of src)for(const e of s.entries||[])for(const a of e.artists||[]){const n=clean(a),id=n.toLowerCase();if(!n)continue;const x=m.get(id)||{artist:n,appearances:0,totalPoints:0,bestRank:null,charts:0};x.appearances++;x.totalPoints+=Math.max(0,101-e.rank);x.bestRank=x.bestRank===null?e.rank:Math.min(x.bestRank,e.rank);x.charts++;m.set(id,x);}return[...m.values()].sort((a,b)=>b.totalPoints-a.totalPoints||b.appearances-a.appearances||a.bestRank-b.bestRank).map((x,i)=>({...x,rank:i+1}));}
async function main(){await mkdir(DATA_DIR,{recursive:true});await mkdir(HISTORY_DIR,{recursive:true});const at=new Date().toISOString();let previous=null;try{previous=JSON.parse(await readFile(LATEST,'utf8'));}catch{}const results=await Promise.all(SOURCES.map(async s=>{try{const raw=await fetchSource(s),old=previous?.sources?.find(x=>x.id===s.id),entries=movement(raw,old);console.log(`OK ${s.name}: ${entries.length}`);return{id:s.id,name:s.name,type:s.type,sourceUrl:s.url,dataUrl:s.dataUrl||null,status:'ok',fetchedAt:at,count:entries.length,entries};}catch(e){const msg=e instanceof Error?e.message:String(e);console.error(`ERROR ${s.name}: ${msg}`);return{id:s.id,name:s.name,type:s.type,sourceUrl:s.url,dataUrl:s.dataUrl||null,status:'error',fetchedAt:at,count:0,error:msg,entries:[]};}}));const ok=results.filter(x=>x.status==='ok'),payload={schemaVersion:3,generatedAt:at,sources:results,artistRankings:artistRankings(ok)};await writeFile(LATEST,JSON.stringify(payload,null,2)+'\n');if(ok.length){const date=at.slice(0,10);await writeFile(new URL(`./${date}.json`,HISTORY_DIR),JSON.stringify(payload,null,2)+'\n');let idx=[];try{idx=JSON.parse(await readFile(HISTORY_INDEX,'utf8'));}catch{}if(!idx.includes(date))idx.push(date);idx.sort().reverse();await writeFile(HISTORY_INDEX,JSON.stringify(idx,null,2)+'\n');}console.log(`Updated ${ok.length}/${results.length} sources at ${at}`);}
main().catch(e=>{console.error(e);process.exit(1);});
