import { mkdir, writeFile, readFile } from 'node:fs/promises';
const ROOT = new URL('..', import.meta.url), DATA_DIR = new URL('./data/', ROOT), LATEST = new URL('./data/latest.json', ROOT), HISTORY_DIR = new URL('./data/history/', ROOT), HISTORY_INDEX = new URL('./data/history/index.json', ROOT);
const YOUTUBE_URL = 'https://charts.youtube.com/youtubei/v1/browse?alt=json&key=AIzaSyCzEW7JUJdSql-0-2V4tHUb6laYm4iAE_dM';
const SOURCES = [
{ id:'spotify-global-daily',name:'Spotify Global Daily',type:'daily',url:'https://charts.spotify.com/charts/view/regional-global-daily/latest/download',parser:parseSpotifyCsv },
{ id:'spotify-global-weekly',name:'Spotify Global Weekly Top Songs',type:'weekly',url:'https://charts.spotify.com/charts/view/regional-global-weekly/latest/download',parser:parseSpotifyCsv },
{ id:'apple-global-daily',name:'Apple Music Global Top 100',type:'daily',url:'https://rss.applemarketingtools.com/api/v2/us/music/most-played/100/songs.json',parser:parseAppleRss },
{ id:'apple-australia-daily',name:'Apple Music Australia Top 100',type:'daily',url:'https://rss.applemarketingtools.com/api/v2/au/music/most-played/100/songs.json',parser:parseAppleRss },
{ id:'youtube-global-daily',name:'YouTube Global Top Songs Daily',type:'daily',url:YOUTUBE_URL,parser:parseYouTubeApi,parserArgs:{chart:'daily',kind:'tracks'} },
{ id:'youtube-global-weekly',name:'YouTube Global Top Songs Weekly',type:'weekly',url:YOUTUBE_URL,parser:parseYouTubeApi,parserArgs:{chart:'weekly',kind:'tracks'} },
{ id:'youtube-global-artists-weekly',name:'YouTube Global Top Artists Weekly',type:'weekly',url:YOUTUBE_URL,parser:parseYouTubeApi,parserArgs:{chart:'weekly',kind:'artists'} },
{ id:'deezer-global',name:'Deezer Global Top Tracks',type:'daily',url:'https://api.deezer.com/chart/0/tracks?limit=100',parser:parseDeezerJson },
{ id:'shazam-us-weekly',name:'Shazam US Top 200',type:'weekly',url:'https://www.shazam.com/services/charts/csv/top-200/united-states',parser:parseShazamCsv },
{ id:'aria-australia-weekly',name:'ARIA Top 50 Singles',type:'weekly',url:'https://www.aria.com.au/charts/singles-chart',parser:parseAriaHtml },
{ id:'official-uk-singles-weekly',name:'Official UK Singles Top 100',type:'weekly',url:'https://www.officialcharts.com/charts/singles-chart/',parser:parseOfficialChartsHtml },
{ id:'billboard-hot-100',name:'Billboard Hot 100',type:'weekly',url:'https://www.billboard.com/charts/hot-100/',dataUrl:'https://raw.githubusercontent.com/mhollingshead/billboard-hot-100/main/recent.json',parser:parseBillboardJson },
{ id:'billboard-global-200',name:'Billboard Global 200',type:'weekly',url:'https://www.billboard.com/charts/billboard-global-200/',dataUrl:'https://raw.githubusercontent.com/KoreanThinker/billboard-json/main/billboard-global-200/recent.json',parser:parseBillboardJson }
];
const HEADERS={'user-agent':'StrettoCharts/1.0 (+https://github.com/Tezzaaaaaa/StrettoCharts)',accept:'text/html,application/json,text/csv;q=0.9,*/*;q=0.8'};
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const strip=v=>clean(String(v??'').replace(/<[^>]+>/g,''));
const key=(t,a=[])=>`${clean(t).toLowerCase()}::${a.map(clean).join('|').toLowerCase()}`;
function csvRows(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){field+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(field);field='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(field);field='';if(row.some(v=>clean(v)))rows.push(row);row=[];}else field+=c;}if(field||row.length){row.push(field);rows.push(row);}return rows;}
function parseSpotifyCsv(text){const r=csvRows(text);if(r.length<2)throw Error('Spotify CSV contained no rows');const h=r[0].map(clean),idx=n=>h.findIndex(x=>x.toLowerCase()===n),rank=idx('rank'),title=idx('track_name'),artist=idx('artist_names'),streams=idx('streams'),date=idx('date'),region=idx('region');if(rank<0||title<0||artist<0)throw Error(`Unexpected Spotify CSV schema: ${h.slice(0,12).join(', ')}`);return r.slice(1).map(x=>({rank:Number(x[rank]),title:clean(x[title]),artists:clean(x[artist]).split(',').map(clean).filter(Boolean),streams:streams>=0?Number(x[streams])||null:null,chartDate:date>=0?clean(x[date]):null,region:region>=0?clean(x[region]):'Global'})).filter(x=>Number.isFinite(x.rank)&&x.title);}
function parseAppleRss(text){const j=JSON.parse(text),r=Array.isArray(j.feed?.results)?j.feed.results:[];return r.map((x,i)=>({rank:i+1,title:clean(x.name),artists:[clean(x.artistName)].filter(Boolean),album:clean(x.collectionName)||null,url:x.url||null,artworkUrl:x.artworkUrl100||null,chartDate:j.feed?.updated||null})).filter(x=>x.title);}
function parseDeezerJson(text){const j=JSON.parse(text),r=Array.isArray(j.data)?j.data:[];return r.map((x,i)=>({rank:i+1,title:clean(x.title),artists:[clean(x.artist?.name)].filter(Boolean),album:clean(x.album?.title)||null,url:x.link||null,artworkUrl:x.album?.cover_medium||null})).filter(x=>x.title);}
function youtubeBody(chart,kind){const type=chart==='daily'?'daily':'weekly';return{browseId:'FEmusic_analytics_charts_home',context:{capabilities:{},client:{clientName:'WEB_MUSIC_ANALYTICS',clientVersion:'0.2',experimentIds:[],experimentsToken:'',gl:'US',hl:'en',theme:'MUSIC'},request:{internalExperimentFlags:[]}},query:`chart_params_type=${type==='daily'?'DAY':'WEEK'}&perspective=CHART&flags=viral_video_chart&selected_chart=${kind==='artists'?'ARTISTS':'TRACKS'}&chart_params_id=${type}:0:0`};}
function parseYouTubeApi(text,args){const j=JSON.parse(text),root=j?.contents?.sectionListRenderer?.contents?.[0]?.musicAnalyticsSectionRenderer;if(!root)throw Error('YouTube Charts API response missing musicAnalyticsSectionRenderer');const c=root.content||{};if(args.kind==='artists'){const v=c.artists?.[0]?.artistViews;if(!Array.isArray(v))throw Error('YouTube artist chart response missing artistViews');return v.map((x,i)=>({rank:Number(x.rank??i+1),title:clean(x.name||x.title||x.artist),artists:[clean(x.name||x.title||x.artist)].filter(Boolean)})).filter(x=>x.rank>0&&x.title).slice(0,100);}const v=c.trackTypes?.[0]?.trackViews;if(!Array.isArray(v))throw Error('YouTube song chart response missing trackViews');return v.map((x,i)=>({rank:Number(x.rank??i+1),title:clean(x.title||x.name),artists:Array.isArray(x.artists)?x.artists.map(a=>clean(a.name||a.title||a)).filter(Boolean):[clean(x.artist)].filter(Boolean)})).filter(x=>x.rank>0&&x.title).slice(0,200);}
function parseShazamCsv(text){const r=csvRows(text);if(r.length<2)throw Error('Shazam CSV contained no rows');const h=r[0].map(clean).map(x=>x.toLowerCase()),find=(...n)=>n.map(x=>h.indexOf(x)).find(i=>i>=0)??-1,rank=find('rank','position'),title=find('title','track','song'),artist=find('artist','artist name','artists');if(title<0||artist<0)throw Error(`Unexpected Shazam CSV schema: ${h.slice(0,15).join(', ')}`);return r.slice(1).map((x,i)=>({rank:rank>=0?Number(x[rank]):i+1,title:clean(x[title]),artists:clean(x[artist]).split(/,|&/).map(clean).filter(Boolean)})).filter(x=>Number.isFinite(x.rank)&&x.title&&x.artists.length).slice(0,200);}
function parseAriaHtml(text){const s=text.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,'\n').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"');const l=s.split(/\n+/).map(clean).filter(Boolean),o=[];for(let i=0;i<l.length&&o.length<50;i++){if(!/^\d+$/.test(l[i]))continue;const rank=Number(l[i]),title=l[i+1],artist=l[i+2];if(rank>=1&&rank<=50&&title&&artist&&!/^\d+$/.test(title))o.push({rank,title,artists:artist.split(',').map(clean).filter(Boolean)});}if(!o.length)throw Error('ARIA markup did not expose chart rows');return dedupe(o);}
function parseOfficialChartsHtml(text){const s=text.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,'\n').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"');const l=s.split(/\n+/).map(clean).filter(Boolean),o=[];for(let i=0;i<l.length&&o.length<100;i++){if(!/^Number\s*\d+$/i.test(l[i]))continue;const rank=Number(l[i].match(/\d+/)[0]),title=l[i+1],artist=l[i+2];if(title&&artist)o.push({rank,title,artists:artist.split(/[\/]/).map(clean).filter(Boolean)});}if(!o.length)throw Error('Official Charts markup did not expose chart rows');return dedupe(o);}
function parseBillboardJson(text){const j=JSON.parse(text),r=Array.isArray(j.data)?j.data:[];if(!r.length)throw Error('Billboard JSON contained no chart rows');return r.map(x=>({rank:Number(x.this_week??x.rank),title:clean(x.song??x.name),artists:clean(x.artist).split(/,|&/).map(clean).filter(Boolean),previousRank:x.last_week??x.last_week_rank??null,peakRank:x.peak_position??x.peak_rank??null,weeksOnChart:x.weeks_on_chart??null,chartDate:j.date??null})).filter(x=>Number.isFinite(x.rank)&&x.title&&x.artists.length);}
function dedupe(rows){return[...new Map(rows.map(x=>[x.rank,x])).values()].sort((a,b)=>a.rank-b.rank);}
async function fetchSource(s){const url=s.dataUrl||s.url,opt={headers:{...HEADERS}};if(s.id.startsWith('youtube-')){opt.method='POST';opt.headers['content-type']='application/json';opt.body=JSON.stringify(youtubeBody(s.parserArgs.chart,s.parserArgs.kind));}const res=await fetch(url,opt);if(!res.ok)throw Error(`HTTP ${res.status} from ${url}`);const entries=s.id.startsWith('youtube-')?s.parser(await res.text(),s.parserArgs):s.parser(await res.text());if(!entries.length)throw Error('No chart entries parsed');return entries;}
function addMovement(current,previous){const old=new Map((previous?.entries||[]).map(e=>[key(e.title,e.artists),e]));return current.map(e=>{const p=old.get(key(e.title,e.artists)),movement=p?p.rank-e.rank:null;return{...e,previousRank:e.previousRank??p?.rank??null,movement,movementLabel:movement===null?'new':movement>0?`up ${movement}`:movement<0?`down ${Math.abs(movement)}`:'same',peakRank:Math.min(e.peakRank??e.rank,p?.peakRank??e.rank),weeksOnChart:e.weeksOnChart??((p?.weeksOnChart||0)+1)};});}
function calculateArtistRankings(sources){const map=new Map();for(const s of sources)for(const e of s.entries||[])for(const a of e.artists||[]){const name=clean(a);if(!name)continue;const id=name.toLowerCase(),row=map.get(id)||{artist:name,appearances:0,totalPoints:0,bestRank:null,charts:0};row.appearances++;row.totalPoints+=Math.max(0,101-e.rank);row.bestRank=row.bestRank===null?e.rank:Math.min(row.bestRank,e.rank);row.charts++;map.set(id,row);}return[...map.values()].sort((a,b)=>b.totalPoints-a.totalPoints||b.appearances-a.appearances||a.bestRank-b.bestRank).map((x,i)=>({...x,rank:i+1}));}
async function main(){await mkdir(DATA_DIR,{recursive:true});await mkdir(HISTORY_DIR,{recursive:true});const updatedAt=new Date().toISOString();let previous=null;try{previous=JSON.parse(await readFile(LATEST,'utf8'));}catch{}const results=await Promise.all(SOURCES.map(async s=>{try{const raw=await fetchSource(s),old=previous?.sources?.find(x=>x.id===s.id),entries=addMovement(raw,old);console.log(`OK ${s.name}: ${entries.length}`);return{id:s.id,name:s.name,type:s.type,sourceUrl:s.url,dataUrl:s.dataUrl||null,status:'ok',fetchedAt:updatedAt,count:entries.length,entries};}catch(error){const message=error instanceof Error?error.message:String(error);console.error(`ERROR ${s.name}: ${message}`);return{id:s.id,name:s.name,type:s.type,sourceUrl:s.url,dataUrl:s.dataUrl||null,status:'error',fetchedAt:updatedAt,count:0,error:message,entries:[]};}}));const ok=results.filter(x=>x.status==='ok'),payload={schemaVersion:3,generatedAt:updatedAt,sources:results,artistRankings:calculateArtistRankings(ok)};await writeFile(LATEST,JSON.stringify(payload,null,2)+'\n','utf8');if(ok.length){const date=updatedAt.slice(0,10);await writeFile(new URL(`./${date}.json`,HISTORY_DIR),JSON.stringify(payload,null,2)+'\n','utf8');let index=[];try{index=JSON.parse(await readFile(HISTORY_INDEX,'utf8'));}catch{}if(!index.includes(date))index.push(date);index.sort().reverse();await writeFile(HISTORY_INDEX,JSON.stringify(index,null,2)+'\n','utf8');}console.log(`Updated ${ok.length}/${results.length} sources at ${updatedAt}`);}
main().catch(error=>{console.error(error);process.exit(1);});
